### ISSUE TITLE
Cannot create new classifier

### ISSUE THREAD

**Issue by gemmell** [LexPredict/lexpredict-legal-dictionary#5]
Class Name is required, it's a select, but it has no values. 

![image](https://user-images.githubusercontent.com/3324817/30684559-050c5ddc-9ef5-11e7-8e34-df8604de7b06.png)

**Comment by mjbommar** [comment]
HI @gemmell , can you please move these issues to the `lexpredict-contraxsuite` repository?  This repository should only be used for issues related to master data, such as terms or countries.
