### ISSUE TITLE
Cannot cluster text units

### ISSUE THREAD

**Issue by gemmell** [LexPredict/lexpredict-legal-dictionary#6]
The "cluster by" field is somewhat broken. I think it's supposed to be a drop down, instead it's a text field.
![image](https://user-images.githubusercontent.com/3324817/30691596-9a3c8e7a-9f0b-11e7-9159-803736a0ce57.png)

Even if I type "terms" into that it doesn't work.

**Comment by gemmell** [comment]
Ah, the problem is that there is a select field there but it is display=none

**Comment by mjbommar** [comment]
HI @gemmell , can you please move these issues to the `lexpredict-contraxsuite` repository?  This repository should only be used for issues related to master data, such as terms or countries.
